cbl-dart/cbl-dart

- packages/cbl/README.md
- packages/cbl/example/lib/main.dart
- packages/cbl/lib/src/couchbase_lite.dart
- packages/cbl/lib/src/document/blob.dart
- packages/cbl/lib/src/document/common.dart
- packages/cbl/lib/src/document/document.dart
- packages/cbl/lib/src/fleece/containers.dart
- packages/cbl/lib/src/fleece/decoder.dart
- packages/cbl/lib/src/fleece/encoder.dart
- packages/cbl/lib/src/fleece/slice.dart
- packages/cbl/lib/src/log/console_logger.dart
- packages/cbl/lib/src/log/file_logger.dart
- packages/cbl/lib/src/log/logger.dart
- packages/cbl/lib/src/replication/replicator.dart
- packages/cbl/lib/src/support/async_callback.dart
- packages/cbl/lib/src/support/debug.dart
- packages/cbl/lib/src/support/ffi.dart
- packages/cbl/lib/src/support/native_object.dart
- packages/cbl_e2e_tests/lib/src/fleece/integration_test.dart
- packages/cbl_e2e_tests/lib/src/test_binding.dart
- packages/cbl_ffi/lib/src/bindings.dart
- packages/cbl_flutter/README.md
- packages/cbl_flutter/example/lib/main.dart
- Rename `CouchbaseLite.initialize` to `init`
- Throw exception when package is used before calling `CouchbaseLite.init`
Closes #100
> feat!: new `CouchbaseLite` API

- native/cbl-dart/src/CBL+Dart.cpp
- native/cbl-dart/src/CBL+Dart.h
- packages/cbl/lib/src/document/blob.dart
- packages/cbl/lib/src/fleece/slice.dart
- packages/cbl/lib/src/support/native_object.dart
- packages/cbl_ffi/lib/src/base.dart
- packages/cbl_ffi/lib/src/blob.dart
- packages/cbl_ffi/lib/src/replicator.dart
- close stream in dart finalizer
- don't copy read buffer unnecessarily
Closes #47
> feat: improve `_BlobReadStreamController`

- native/cbl-dart/src/CBL+Dart.cpp
- Actually run logic in `CBLDart_Init` only once.
- Fix word in log file config warning.
> fix: only initialize console log level once

- packages/cbl/lib/src/replication/ffi_replicator.dart
- packages/cbl_e2e_tests/lib/src/replication/replicator_test.dart
- packages/cbl_e2e_tests/lib/src/utils/replicator_utils.dart
- packages/cbl_e2e_tests/lib/src/utils/test_document.dart
Workaround for a bug in Couchbase Lite which can cause a crash when stopping a replicator while it is connecting.
> fix: do not stop replicator while it is connecting

- native/cbl-dart/src/CBL+Dart.cpp
- native/cbl-dart/src/CBL+Dart.h
- packages/cbl/lib/src/init.dart
- packages/cbl_ffi/lib/src/base.dart
With this change `CBLDart_Initialize` can be called multiple times, but only initializes the native libraries once. This is necessary to allow hot restarting of Flutter apps, where only the Dart Isolates are fully restarted, but native libraries remain loaded.
Fixes #175
> fix: initialize native libraries exactly once

- packages/cbl/lib/src/document/array.dart
- packages/cbl/lib/src/document/dictionary.dart
- packages/cbl/lib/src/document/document.dart
- packages/cbl_e2e_tests/lib/src/document/array_test.dart
- packages/cbl_e2e_tests/lib/src/document/dictionary_test.dart
- packages/cbl_e2e_tests/lib/src/document/document_test.dart
With this change, containers which are already mutable don't just return themselves from `toMutable`, but instead return a mutable deep copy.
Closes #136
> feat: return mutable copies from `toMutable` methods

- packages/cbl/lib/src/query/ffi_query.dart
- packages/cbl/lib/src/query/proxy_query.dart
- packages/cbl/lib/src/query/query.dart
- packages/cbl/lib/src/query/select.dart
- packages/cbl_e2e_tests/lib/src/query/query_test.dart
> fix: ensure query is prepared by listening to `changes` stream

- .github/workflows/ci.yaml
- README.md
- packages/cbl/README.md
- packages/cbl_dart/CHANGELOG.md
- packages/cbl_dart/LICENSE
- packages/cbl_dart/README.md
- packages/cbl_dart/example/.gitignore
- packages/cbl_dart/example/README.md
- packages/cbl_dart/example/bin/cbl_dart_example.dart
- packages/cbl_dart/example/lib/main.dart
- packages/cbl_dart/example/pubspec.yaml
- packages/cbl_dart/lib/cbl_dart.dart
- packages/cbl_dart/lib/src/acquire_libraries.dart
- packages/cbl_dart/lib/src/install_libraries.dart
- packages/cbl_dart/lib/src/package.dart
- packages/cbl_dart/lib/src/tools.dart
- packages/cbl_dart/lib/src/utils.dart
- packages/cbl_dart/pubspec.yaml
- packages/cbl_dart/test/init_with_files_dir_test.dart
- packages/cbl_dart/test/init_with_native_libraries_dir_test.dart
- packages/cbl_dart/test/init_without_files_dir_test.dart
- packages/cbl_dart/test/init_without_native_libraries_dir_test.dart
- packages/cbl_dart/test/install_libraries_test.dart
- packages/cbl_flutter/README.md
This packages allows pure Dart apps to use Couchbase Lite withouth having to manually manage the native libraries.
> feat: add `cbl_dart` package

- native/couchbase-lite-dart/include/CBL+Dart.h
- native/couchbase-lite-dart/include/Fleece+Dart.h
- native/couchbase-lite-dart/src/CBL+Dart.cpp
- native/couchbase-lite-dart/src/Fleece+Dart.cpp
- native/couchbase-lite-dart/src/Sentry.cpp
- native/couchbase-lite-dart/src/Utils.cpp
- native/couchbase-lite-dart/src/Utils.h
- make all file private functions and variables `static`
- relocate utility functions to `Utils.h|cpp`
- make section comments consistent
> refactor: clean up `libcblitedart`

- native/couchbase-lite-dart/src/CBL+Dart.cpp
> fix: only call Dart log callback if registered

- packages/cbl/lib/src/database/blob_store.dart
- packages/cbl/lib/src/database/database.dart
- packages/cbl/lib/src/database/ffi_blob_store.dart
- packages/cbl/lib/src/database/ffi_database.dart
- packages/cbl/lib/src/database/proxy_blob_store.dart
- packages/cbl/lib/src/database/proxy_database.dart
- packages/cbl/lib/src/document/blob.dart
- packages/cbl/lib/src/service/cbl_service.dart
- packages/cbl/lib/src/service/cbl_service_api.dart
- packages/cbl/lib/src/support/streams.dart
- packages/cbl/test/support/streams_test.dart
- packages/cbl_e2e_tests/lib/src/database/database_test.dart
- packages/cbl_e2e_tests/lib/src/document/blob_test.dart
- packages/cbl_ffi/lib/src/base.dart
This change adds the methods `Database.saveBlob` and `Database.getBlob`.
They allow saving and retrieving `Blob`s, independently of `Document`s.
This is a breaking change because `Blob.fromStream` is now a factory
instead of a static method returning a `Future`. To get the previous
behavior, create a `Blob` with `Blob.fromStream` and save it with
`Database.saveBlob`.
This change also fixes `Blob.isBlob`.
`Blob.properties` now returns a `Map` that contains full `Blob`
metadata.
Closes #255
Closes #253
> feat!: Add `Database.saveBlob` and `Database.getBlob`

- packages/cbl_flutter/README.md
- `setUpAll` has wrong casing
- `CouchbaseLiteDart.init` misses `await`, making the test fail (DB not initialized)
> Fixing CBL Flutter test example in README.md

- packages/cbl/lib/src/errors.dart
- packages/cbl/lib/src/service/channel.dart
> feat: make remote stack traces available separately instead of throwing with them

- packages/cbl/lib/src/query/query.dart
- packages/cbl_e2e_tests/lib/src/query/query_test.dart
> feat: make source N1QL query string available on `Query` 

- .github/workflows/ci.yaml
- native/couchbase-lite-dart/include/CBL+Dart.h
- native/couchbase-lite-dart/include/Fleece+Dart.h
- native/couchbase-lite-dart/src/CBL+Dart.cpp
- native/couchbase-lite-dart/src/Fleece+Dart.cpp
- native/couchbase-lite-dart/src/Utils.cpp
- native/couchbase-lite-dart/src/Utils.h
- packages/cbl_ffi/lib/src/base.dart
- packages/cbl_ffi/lib/src/blob.dart
- packages/cbl_ffi/lib/src/c_type.dart
- packages/cbl_ffi/lib/src/database.dart
- packages/cbl_ffi/lib/src/document.dart
- packages/cbl_ffi/lib/src/fleece.dart
- packages/cbl_ffi/lib/src/global.dart
- packages/cbl_ffi/lib/src/logging.dart
- packages/cbl_ffi/lib/src/query.dart
- packages/cbl_ffi/lib/src/replicator.dart
- packages/cbl_ffi/lib/src/tracing.dart
We need to wait for Dart 2.16.0 to be come the stabel version, before merging this PR.
An incompatibility of `package:ffi` with `win32` blocks this PR for Flutter, currently.
Closes  #139
> refactor: remove native type conversions  

- packages/cbl/lib/src/database/proxy_database.dart
- packages/cbl/lib/src/document/ffi_document.dart
- packages/cbl/lib/src/document/proxy_document.dart
- packages/cbl/lib/src/query/proxy_query.dart
- packages/cbl/lib/src/query/result.dart
- packages/cbl/lib/src/replication/proxy_replicator.dart
- packages/cbl/lib/src/service/cbl_service.dart
- packages/cbl/lib/src/service/cbl_service_api.dart
- packages/cbl_e2e_tests/lib/src/utils/database_utils.dart
- packages/cbl_ffi/lib/src/fleece.dart
This change adds `TransferableValue`, which can be used to transfer `EncodedData` or a Fleece `Value` by its address between isolates.
When isolates are in the same process (as is the case for `WorkerDatabase`), a `TransferableValue` does not require copying.
Closes #309
> perf: transfer data without copying where possible

- packages/cbl/lib/src/document/common.dart
- packages/cbl/lib/src/query/ffi_query.dart
- packages/cbl/lib/src/query/proxy_query.dart
- packages/cbl/lib/src/query/result_set.dart
> fix: use own `SharedKeysTable` for each `ResultSet`

- packages/cbl/lib/src/support/async_callback.dart
The reachability fence in `AsyncCallback.close` was keeping `native` alive,
which in this case is just a wrapper for the pointer and not the Dart object that is
used for finalization. Now `this` is used to ensure that the `AsyncCallback`
finalizer is not running while `_bindings.close` is.
> fix: keep `AsyncCallback` reachable in `close`

- packages/cbl/lib/src/document/common.dart
- packages/cbl/lib/src/document/document.dart
- packages/cbl/lib/src/document/ffi_document.dart
- packages/cbl/lib/src/document/proxy_document.dart
- packages/cbl/lib/src/fleece/dict_key.dart
- packages/cbl/lib/src/fleece/integration/array.dart
- packages/cbl/lib/src/fleece/integration/collection.dart
- packages/cbl/lib/src/fleece/integration/context.dart
- packages/cbl/lib/src/fleece/integration/dict.dart
- packages/cbl/lib/src/fleece/integration/root.dart
- packages/cbl/lib/src/fleece/integration/value.dart
- packages/cbl/lib/src/query/ffi_query.dart
- packages/cbl/lib/src/query/result.dart
- packages/cbl_e2e_tests/lib/src/document/array_test.dart
- packages/cbl_e2e_tests/lib/src/document/dictionary_test.dart
- packages/cbl_e2e_tests/lib/src/document/document_test.dart
- packages/cbl_e2e_tests/lib/src/document/document_test_utils.dart
- packages/cbl_e2e_tests/lib/src/fleece/decoding_benchmark_test.dart
- packages/cbl_e2e_tests/lib/src/fleece/encoding_benchmark_test.dart
- packages/cbl_e2e_tests/lib/src/fleece/integration_test.dart
- packages/cbl_e2e_tests/lib/src/query/result_test.dart
Other notable changes:
- Use sentinel for empty native value in `MValue`.
- Retain Fleece data in `MContext`.
> feat: support sharing mutable collections with multiple documents

- packages/cbl_ffi/lib/src/base.dart
- packages/cbl_ffi/lib/src/fleece.dart
- packages/cbl_ffi/lib/src/logging.dart
- packages/cbl_ffi/lib/src/replicator.dart
> fix: allow malformed UTF-8 in log and error messages

- packages/cbl_flutter/lib/cbl_flutter.dart
`Error` (not `Exception`) should not be caught by `try/catch` or `onError`. [See more](https://api.dart.dev/stable/2.4.0/dart-core/Error-class.html)
As `getExternalStorageDirectory` method is not supported on iOS we must never call the method on iOS platform.
> Fix UnsupportedError during initialization

- packages/cbl/lib/src/database/database.dart
- packages/cbl/lib/src/database/ffi_database.dart
- packages/cbl/pubspec.yaml
- packages/cbl_e2e_tests/lib/src/database/database_test.dart
> fix: don't require trailing path separator when copying databases

- packages/cbl/lib/src/database/database_base.dart
- packages/cbl/lib/src/replication/document_replication.dart
This addresses an issue where after the ending of a transaction failed, the exception handler tried to end the transaction again.
> fix: end transactions exactly once

- packages/cbl/lib/src/replication/ffi_replicator.dart
Dart SDK issue: https://github.com/dart-lang/sdk/issues/54414
> fix: workaround Dart bug when destructuring record containing `Finalizable`

- docs/docs/databases.mdx
- packages/cbl/lib/src/log.dart
- packages/cbl/lib/src/log/logger.dart
- packages/cbl_dart/lib/cbl_dart.dart
- packages/cbl_e2e_tests/lib/src/log/logger_test.dart
- packages/cbl_e2e_tests/lib/src/test_binding.dart
- packages/cbl_e2e_tests_flutter/integration_test/test_binding_impl.dart
- packages/cbl_flutter/lib/cbl_flutter.dart
Since the builtin console logger now logs to logcat on Android the `DartConsoleLogger` is no longer necessary to support console logs on all platforms.
> feat!: remove `DartConsoleLogger` and stop initializing `Database.log.custom` with it

- packages/cbl_e2e_tests_flutter/android/app/build.gradle
- packages/cbl_flutter_prebuilt_e2e_tests/android/app/build.gradle
> test: upgrade to `compileSdk = 34` to allow running integration tests again

- packages/cbl_flutter/lib/cbl_flutter.dart
Before this change, the external app directory was used for the `CBLTemp` directory on Android. Accessing the external app directory requires different permissions on different versions of Android, but we never requested any permissions. By using the internal app directory, no permissions are necessary on any version of Android.
> fix: put `CBLTemp` directory in application support directory

- packages/cbl/lib/src/bindings/query.dart
- packages/cbl_e2e_tests/lib/src/query/index_updater_test.dart
> fix: error handling for `QueryIndex.beginUpdate`

- packages/cbl/lib/src/install/utils.dart
- packages/cbl/test/install/package_test.dart
- packages/cbl/test/install/utils_test.dart
- packages/cbl/test/utils.dart
> fix: ensure `copyDirectoryContents` can overwrite links on all platforms

- packages/cbl/lib/src/database/proxy_database.dart
- packages/cbl/lib/src/document/proxy_document.dart
This was necessary with the approach used for finalizing Dart objects
before `Finalizer` was available in the Dart SDK.
> refactor: stop registering documents with `ProxyDatabase` for clean up

- packages/cbl/lib/src/service/object_registry.dart
`ObjectRegistry` has a mapping from `Object` to `int` and from `int` to `Object`, but removing an object from the registry only removed in from one of the mappings.
> fix: memory leak in `ObjectRegistry`

- packages/cbl/lib/src/service/cbl_service.dart
- packages/cbl/lib/src/service/cbl_service_api.dart
- packages/cbl/lib/src/support/listener_token.dart
- packages/cbl_e2e_tests/lib/src/service/cbl_service_api_test.dart
Also, improve `NotFoundException.message` slightly.
> refactor: consistently use `getObjectOrThrow` to find objects in `ObjectRegistry`
