packages/cbl/README.md
packages/cbl/example/lib/main.dart
packages/cbl/lib/cbl.dart
packages/cbl/lib/src/couchbase_lite.dart
packages/cbl/lib/src/database.dart
packages/cbl/lib/src/worker/cbl_worker.dart
packages/cbl/lib/src/worker/worker.dart
packages/cbl_e2e_tests/lib/src/blob_test.dart
packages/cbl_e2e_tests/lib/src/database_test.dart
packages/cbl_e2e_tests/lib/src/log_test.dart
packages/cbl_e2e_tests/lib/src/replicator_test.dart
packages/cbl_e2e_tests/lib/src/test_binding.dart
packages/cbl_flutter/example/lib/main.dart

BREAKING CHANGE: APIs of `Database` and `CouchbaseLite`

feat(cbl): improve `CouchbaseLite` and `Database` APIs

---

packages/cbl_e2e_tests/lib/src/fleece_test.dart
packages/cbl_ffi/lib/src/fleece.dart

fix(cbl_ffi): fix size of result of FLValue_AsInt_C

---

packages/cbl/lib/src/errors.dart
packages/cbl_e2e_tests/lib/src/database_test.dart

feat(cbl): highlight error position in query parsing exception

---

packages/cbl/lib/src/replicator.dart

Also cleans up a few things in `replicator.dart`.
Fixes #34

fix(cbl): fix `Replicator` conflict resolver callback

---

packages/cbl_flutter/android/build.gradle
packages/cbl_flutter/tool/install_binaries.sh
packages/cbl_native/lib/cbl_native.dart
packages/cbl_native/pubspec.yaml

fix(cbl_flutter): installing binaires on windows

---

packages/cbl_flutter/tool/install_binaries.sh

fix(cbl_flutter): fix variable reference in `install_binaries.sh`

---

.github/actions/setup-dart-env/action.yml
.github/workflows/ci.yaml
.vscode/launch.json
melos.yaml
native/cbl-dart/src/CBL+Dart.cpp
native/cbl-dart/src/CBL+Dart.h
native/cbl-dart/src/Fleece+Dart.cpp
native/cbl-dart/src/Fleece+Dart.h
packages/cbl_e2e_tests/lib/src/logging_test.dart
packages/cbl_e2e_tests/lib/src/utils/replicator_utils.dart
packages/cbl_ffi/lib/src/blob.dart
packages/cbl_ffi/lib/src/fleece.dart

ci: run e2e tests on android emulator

---

packages/cbl_e2e_tests/lib/src/database_test.dart
packages/cbl_e2e_tests/lib/src/document/array_test.dart
packages/cbl_e2e_tests/lib/src/document/blob_test.dart
packages/cbl_e2e_tests/lib/src/document/dictionary_test.dart
packages/cbl_e2e_tests/lib/src/document/document_test.dart
packages/cbl_e2e_tests/lib/src/document/fragment_test.dart
packages/cbl_e2e_tests/lib/src/fleece/coding_test.dart
packages/cbl_e2e_tests/lib/src/fleece/containers_test.dart
packages/cbl_e2e_tests/lib/src/fleece/integration_test.dart
packages/cbl_e2e_tests/lib/src/fleece/slice_test.dart
packages/cbl_e2e_tests/lib/src/logging_test.dart
packages/cbl_e2e_tests/lib/src/native_callback_test.dart
packages/cbl_e2e_tests/lib/src/replication/authenticator_test.dart
packages/cbl_e2e_tests/lib/src/replication/configuration_test.dart
packages/cbl_e2e_tests/lib/src/replication/conflict_test.dart
packages/cbl_e2e_tests/lib/src/replication/document_replication_test.dart
packages/cbl_e2e_tests/lib/src/replication/endpoint_test.dart
packages/cbl_e2e_tests/lib/src/replication/replicator_change_test.dart
packages/cbl_e2e_tests/lib/src/replication/replicator_test.dart
packages/cbl_e2e_tests/lib/src/test_binding.dart
packages/cbl_e2e_tests/lib/src/utils/database_utils.dart
packages/cbl_e2e_tests/lib/src/utils/replicator_utils.dart
packages/cbl_e2e_tests/lib/src/utils/test_document.dart
packages/cbl_flutter/example/integration_test/test_binding_impl.dart

test: use functions from `test` package

---

packages/cbl/lib/cbl.dart
packages/cbl/lib/src/couchbase_lite.dart
packages/cbl/lib/src/database.dart
packages/cbl/lib/src/fleece/containers.dart
packages/cbl/lib/src/query.dart
packages/cbl/lib/src/replication/replicator.dart
packages/cbl/lib/src/streams.dart
packages/cbl_e2e_tests/lib/src/native_callback_test.dart

refactor: use `NativeObject.pointer` where possible

---

native/cbl-dart/src/CBL+Dart.cpp
native/cbl-dart/src/CBL+Dart.h
native/cbl-dart/src/Callbacks.cpp
native/cbl-dart/src/Callbacks.h
native/cbl-dart/src/Fleece+Dart.cpp
packages/cbl/lib/src/database.dart
packages/cbl/lib/src/native_callback.dart
packages/cbl/lib/src/replication/replicator.dart
packages/cbl/lib/src/streams.dart
packages/cbl_e2e_tests/lib/src/native_callback_test.dart
packages/cbl_ffi/lib/src/native_callback.dart

Also improves debugging of native callbacks.

fix: ensure native callbacks complete

---

native/tools/build_android.sh
packages/cbl/README.md
packages/cbl_flutter/README.md
packages/cbl_flutter/android/build.gradle
packages/cbl_flutter/example/android/app/build.gradle

feat: require Android API level >= 22

---

.github/workflows/cbl_native-binaries-release.yaml
.github/workflows/ci.yaml
CONTRIBUTING.md
native/cbl-dart/CMakeLists.txt
native/tools/build_unix.sh
packages/cbl/lib/src/couchbase_lite.dart
packages/cbl_e2e_tests_standalone_dart/test/test_binding_impl.dart
packages/cbl_ffi/lib/src/libraries.dart

build: suport building for linux and macOS with `build_unix.sh`

---

native/cbl-dart/src/CBL+Dart.cpp
native/cbl-dart/src/CBL+Dart.h
packages/cbl/lib/src/database/database.dart
packages/cbl/lib/src/support/native_object.dart
packages/cbl_ffi/lib/src/database.dart

- finalizers now close open database
- finalizers now stop replicator

feat: finalize resources in Dart finalizers

---

packages/cbl/lib/src/database/blob_store.dart
packages/cbl/lib/src/database/ffi_blob_store.dart
packages/cbl/lib/src/document/blob.dart
packages/cbl/lib/src/document/common.dart
packages/cbl/lib/src/document/document.dart
packages/cbl/lib/src/document/ffi_document.dart
packages/cbl/lib/src/fleece/containers.dart
packages/cbl/lib/src/fleece/decoder.dart
packages/cbl/lib/src/fleece/encoder.dart
packages/cbl/lib/src/fleece/integration/delegate.dart
packages/cbl/lib/src/fleece/integration/root.dart
packages/cbl/lib/src/query/ffi_query.dart
packages/cbl/lib/src/query/result.dart
packages/cbl/lib/src/replication/ffi_replicator.dart
packages/cbl_e2e_tests/lib/src/document/array_test.dart
packages/cbl_e2e_tests/lib/src/document/dictionary_test.dart
packages/cbl_e2e_tests/lib/src/fleece/coding_test.dart
packages/cbl_e2e_tests/lib/src/fleece/integration_test.dart
packages/cbl_e2e_tests/lib/src/fleece/slice_test.dart
packages/cbl_e2e_tests/lib/src/query/result_test.dart
packages/cbl_e2e_tests/lib/src/utils/fleece_coding.dart
packages/cbl_e2e_tests/lib/src/utils/matchers.dart
packages/cbl_ffi/analysis_options.yaml
packages/cbl_ffi/lib/cbl_ffi.dart
packages/cbl_ffi/lib/src/blob.dart
packages/cbl_ffi/lib/src/data.dart
packages/cbl_ffi/lib/src/fleece.dart
packages/cbl_ffi/lib/src/replicator.dart
packages/cbl_ffi/lib/src/slice.dart

refactor: add `Data` abstraction

---

packages/cbl_ffi/lib/cbl_ffi.dart
packages/cbl_ffi/lib/src/base.dart
packages/cbl_ffi/lib/src/replicator.dart

fix: decode error code in `ReplicatorStatusCallbackMessage.parseArguments`

---

native/cbl-dart/src/Fleece+Dart.cpp
native/cbl-dart/src/Fleece+Dart.h
packages/cbl/lib/src/fleece/encoder.dart
packages/cbl/lib/src/support/native_object.dart
packages/cbl_ffi/lib/src/fleece.dart

feat: make `FleeceEncoder` a `NativeObject`

---

native/cbl-dart/src/CBL+Dart.cpp
native/cbl-dart/src/CBL+Dart.h
packages/cbl/lib/src/init.dart
packages/cbl_ffi/lib/cbl_ffi.dart
packages/cbl_ffi/lib/src/base.dart
packages/cbl_ffi/lib/src/bindings.dart
packages/cbl_ffi/lib/src/blob.dart
packages/cbl_ffi/lib/src/database.dart
packages/cbl_ffi/lib/src/document.dart
packages/cbl_ffi/lib/src/fleece.dart
packages/cbl_ffi/lib/src/global.dart
packages/cbl_ffi/lib/src/logging.dart
packages/cbl_ffi/lib/src/query.dart
packages/cbl_ffi/lib/src/replicator.dart
packages/cbl_ffi/lib/src/slice.dart
packages/cbl_ffi/lib/src/utils.dart

feat(cbl_ffi): allocate global memory in `SliceResult`

---

.github/workflows/ci.yaml
packages/cbl/lib/src/replication.dart
packages/cbl/lib/src/replication/endpoint.dart
packages/cbl/lib/src/replication/ffi_replicator.dart
packages/cbl/lib/src/replication/proxy_replicator.dart
packages/cbl/lib/src/service/cbl_service.dart
packages/cbl/lib/src/service/cbl_service_api.dart
packages/cbl/lib/src/support/edition.dart
packages/cbl/test/support/edition_test.dart
packages/cbl_e2e_tests/lib/src/query/query_builder_test.dart
packages/cbl_e2e_tests/lib/src/replication/replicator_test.dart
packages/cbl_e2e_tests/lib/src/utils/api_variant.dart
packages/cbl_e2e_tests/lib/src/utils/database_utils.dart
packages/cbl_e2e_tests_standalone_dart/test/test_binding_impl.dart
packages/cbl_ffi/lib/src/libraries.dart
packages/cbl_ffi/lib/src/replicator.dart
tools/ci-steps.sh

feat: add `DatabaseEndpoint` for local replication

---

native/couchbase-lite-dart/include/CBL+Dart.h
native/couchbase-lite-dart/src/CBL+Dart.cpp
packages/cbl/README.md
packages/cbl/dartdoc_options.yaml
packages/cbl/doc/enterprise-edition.md
packages/cbl/lib/src/database.dart
packages/cbl/lib/src/database/database.dart
packages/cbl/lib/src/database/database_configuration.dart
packages/cbl/lib/src/database/ffi_database.dart
packages/cbl/lib/src/database/proxy_database.dart
packages/cbl/lib/src/query/query.dart
packages/cbl/lib/src/replication/endpoint.dart
packages/cbl/lib/src/service/cbl_service.dart
packages/cbl/lib/src/service/cbl_service_api.dart
packages/cbl_e2e_tests/lib/src/database/database_configuration_test.dart
packages/cbl_e2e_tests/lib/src/database/database_test.dart
packages/cbl_e2e_tests/lib/src/query/query_test.dart
packages/cbl_e2e_tests/lib/src/utils/database_utils.dart
packages/cbl_e2e_tests/lib/src/utils/encryption.dart
packages/cbl_e2e_tests/lib/src/utils/matchers.dart
packages/cbl_ffi/lib/src/database.dart
tools/ci-steps.sh

- Adds `EncryptionKey`
- Adds `DatabaseConfiguration.encryptionKey`
- Adds `Database.changeEncryptionKey`

feat: add support for database encryption

---

native/couchbase-lite-dart/include/CBL+Dart.h
native/couchbase-lite-dart/src/CBL+Dart.cpp
packages/cbl/README.md
packages/cbl/pubspec.yaml
packages/cbl_flutter/README.md
packages/cbl_flutter/pubspec.yaml

docs: exand README

---

packages/cbl/lib/src/document/common.dart
packages/cbl_e2e_tests/lib/src/document/array_test.dart
packages/cbl_e2e_tests/lib/src/document/dictionary_test.dart

fix: correctly update nested collections in documents

---

native/couchbase-lite-dart/src/AsyncCallback.cpp
native/couchbase-lite-dart/src/CBL+Dart.cpp
tools/create-crash-report-linux.sh

fix: add workaround for removing document change listeners

---

packages/cbl/lib/src/query/proxy_query.dart
packages/cbl/lib/src/service/proxy_object.dart
packages/cbl/lib/src/support/resource.dart

fix: allow isolate to exit when database is closed

---

packages/cbl/lib/src/couchbase_lite.dart
packages/cbl/lib/src/query/select.dart
packages/cbl/lib/src/service/cbl_worker.dart
packages/cbl_e2e_tests/lib/src/fleece/coding_test.dart
packages/cbl_e2e_tests/lib/src/query/query_builder_test.dart
packages/cbl_e2e_tests/lib/src/query/query_test.dart
packages/cbl_ffi/lib/src/base.dart
packages/cbl_ffi/lib/src/fleece.dart
packages/cbl_ffi/lib/src/replicator.dart
tools/coverage.sh

- add tests
- remove some unused methods and fields

refactor: improve coverage

---

.github/workflows/ci.yaml
packages/cbl/example/lib/main.dart
packages/cbl/lib/src/couchbase_lite.dart
packages/cbl/lib/src/support/ffi.dart
packages/cbl/lib/src/support/isolate.dart
packages/cbl_dart/lib/src/acquire_libraries.dart
packages/cbl_e2e_tests_standalone_dart/test/test_binding_impl.dart
packages/cbl_ffi/lib/src/bindings.dart
packages/cbl_ffi/lib/src/libraries.dart
packages/cbl_flutter_platform_interface/lib/cbl_flutter_platform_interface.dart
packages/cbl_flutter_platform_interface/lib/standard_cbl_flutter_platform.dart

- Renames `Libraries` to `LibrariesConfiguration`
- Adds `LibraryConfiguration.isAppleFramework`
- Adds `LibrariesConfiguration.directory`
- Load libraries on Windows with `AddDllDirectory`

feat: improve native libraries configuration

---

.github/workflows/ci.yaml
packages/cbl_dart/README.md
packages/cbl_dart/lib/src/acquire_libraries.dart
packages/cbl_dart/lib/src/install_libraries.dart
packages/cbl_dart/lib/src/package.dart
packages/cbl_dart/lib/src/tools.dart
packages/cbl_dart/pubspec.yaml
packages/cbl_dart/test/install_libraries_test.dart
packages/cbl_flutter/README.md

feat: add support for Windows for `cbl_dart`

---

.github/workflows/ci.yaml
packages/cbl_e2e_tests_flutter/integration_test/test_binding_impl.dart
packages/cbl_flutter/README.md
packages/cbl_flutter/example/lib/main.dart
packages/cbl_flutter_platform_interface/lib/cbl_flutter_platform_interface.dart
packages/cbl_flutter_prebuilt_e2e_tests/integration_test/e2e_test.dart

feat: no longer require manual plugin registration for mobile

---

packages/cbl/lib/src/service/channel.dart
packages/cbl/lib/src/tracing.dart
packages/cbl_e2e_tests/lib/src/tracing_test.dart
packages/cbl_flutter/example/lib/main.dart

feat: add `DevToolsTracing` `TracingDelegate`

---

packages/cbl/lib/src/database/proxy_database.dart
packages/cbl/lib/src/document/proxy_document.dart
packages/cbl/lib/src/service/cbl_service.dart
packages/cbl/lib/src/service/cbl_service_api.dart

perf: keep proxied documents in memory

---

packages/cbl/lib/src/service/cbl_service.dart
packages/cbl_e2e_tests/lib/src/database/database_test.dart

fix: resolve proxied document correctly when deleting it

---

packages/cbl/lib/src/document/proxy_document.dart
packages/cbl/lib/src/replication/proxy_replicator.dart
packages/cbl/lib/src/service/cbl_service.dart
packages/cbl/lib/src/service/object_registry.dart
packages/cbl_e2e_tests/lib/src/database/database_test.dart

fix: ensure proxied document can be resolved when saving

---

packages/cbl/lib/src/replication/ffi_replicator.dart
packages/cbl_e2e_tests/lib/src/replication/replicator_test.dart

fix: translate exceptions when creating replicator endpoint with URL

---

native/couchbase-lite-dart/tools/build_android.sh
packages/cbl/lib/src/replication/configuration.dart
packages/cbl/lib/src/replication/ffi_replicator.dart
packages/cbl/lib/src/replication/proxy_replicator.dart
packages/cbl/lib/src/service/cbl_service.dart
packages/cbl/lib/src/service/cbl_service_api.dart
packages/cbl_e2e_tests/lib/src/replication/configuration_test.dart
packages/cbl_e2e_tests/lib/src/replication/replicator_test.dart

feat: add `ReplicatorConfiguration.trustedRootCertificates`

---

native/couchbase-lite-dart/include/CBL+Dart.h
native/couchbase-lite-dart/src/CBL+Dart.cpp
packages/cbl/lib/src/query/ffi_query.dart
packages/cbl/lib/src/replication/ffi_replicator.dart
packages/cbl_ffi/lib/src/query.dart
packages/cbl_ffi/lib/src/replicator.dart

fix: add locking for a number of finalizers

---

packages/cbl/lib/src/errors.dart
packages/cbl/lib/src/service/cbl_service_api.dart
packages/cbl/lib/src/support/errors.dart
packages/cbl_e2e_tests/lib/src/fleece/containers_test.dart
packages/cbl_e2e_tests/lib/src/service/cbl_service_api_test.dart

feat: add `PosixException`, `SQLiteException` and `FleeceException`

---

.github/workflows/ci.yaml
packages/cbl_e2e_tests_flutter/android/app/build.gradle
packages/cbl_e2e_tests_flutter/android/build.gradle
packages/cbl_e2e_tests_flutter/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter/example/android/app/build.gradle
packages/cbl_flutter/example/android/build.gradle
packages/cbl_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter_ce/android/build.gradle
packages/cbl_flutter_ce/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter_ee/android/build.gradle
packages/cbl_flutter_ee/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter_local/android/build.gradle
packages/cbl_flutter_local/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter_prebuilt/template_package/android/build.gradle__template__
packages/cbl_flutter_prebuilt/template_package/android/gradle/wrapper/gradle-wrapper.properties
packages/cbl_flutter_prebuilt_e2e_tests/android/app/build.gradle
packages/cbl_flutter_prebuilt_e2e_tests/android/build.gradle
packages/cbl_flutter_prebuilt_e2e_tests/android/gradle/wrapper/gradle-wrapper.properties

fix: upgrade kotlin version used in Android plugin

---

.github/workflows/ci.yaml
packages/cbl/lib/src/document/blob.dart
packages/cbl/lib/src/query/expressions/expression.dart
packages/cbl/lib/src/query/join.dart
packages/cbl/lib/src/query/query_builder.dart
packages/cbl/pubspec.yaml
packages/cbl_e2e_tests/couchbase-services.sh
packages/cbl_sentry/lib/src/couchbase_lite_integration.dart

…UnmodifiableUint8ListView
Fixes https://github.com/cbl-dart/cbl-dart/issues/598

feat: use `asUnmodifiableView` instead of `UnmodifiableUint8ListView`

---

packages/cbl_flutter_ce/android/build.gradle
packages/cbl_flutter_ce/ios/cbl_flutter_ce.podspec
packages/cbl_flutter_ce/linux/CMakeLists.txt
packages/cbl_flutter_ce/macos/cbl_flutter_ce.podspec
packages/cbl_flutter_ce/windows/CMakeLists.txt
packages/cbl_flutter_ee/android/build.gradle
packages/cbl_flutter_ee/ios/cbl_flutter_ee.podspec
packages/cbl_flutter_ee/linux/CMakeLists.txt
packages/cbl_flutter_ee/macos/cbl_flutter_ee.podspec
packages/cbl_flutter_ee/windows/CMakeLists.txt
packages/cbl_flutter_prebuilt/template_package/android/build.gradle__template__
packages/cbl_flutter_prebuilt/template_package/ios/{{name}}.podspec__template__
packages/cbl_flutter_prebuilt/template_package/linux/CMakeLists.txt__template__
packages/cbl_flutter_prebuilt/template_package/macos/{{name}}.podspec__template__
packages/cbl_flutter_prebuilt/template_package/windows/CMakeLists.txt__template__

fix: resolve absolute path to dart executable Flutter plugin

---

packages/cbl/lib/src/query/proxy_query.dart

In normal operation, proxy objects release their corresponding objects
on the remote side when they are GCed.
The intention of `_ProxyQueryEarlyFinalizer` was to ensure the release of
the `Query` object on the remote side, when the `ProxyDatabase` closes
before the `ProxyQuery` has been GCed.
When the `ProxyDatabase` closes, the `CblService` that potential still
holds on to the `Query` through a `ObjectRegistry`, is soon GCed anyway.
A `WorkerDatabase` tears down its `IsolateWorker` when it closes. Besides
for testing, there currently is no other situation where `CblService` instances
are created.
It turned out that the closing of `_ProxyQueryEarlyFinalizer` is run in parallel with 
closing `ListenerTokenRegistry` and `ProxyListenerToken`s of the same query. 
This caused the `Query` on …

refactor: remove `_ProxyQueryEarlyFinalizer`

---

packages/cbl/lib/src/install/utils.dart
packages/cbl/pubspec.yaml
packages/cbl_generator/pubspec.yaml
packages/cbl_generator/test/generator/typed_database_generator_test.dart
packages/cbl_generator/test/generator/typed_dictionary_generator_test.dart

This allows package consumers to upgrade other dependencies.

deps: widen dependency constraints of `package:source_gen` and `package:archive`

---

docs/docs/queries/query-builder.mdx
docs/docs/queries/sqlplusplus-query-builder-diff.mdx
packages/cbl/lib/src/query/function.dart
packages/cbl_e2e_tests/lib/src/query/query_builder_test.dart

Adds support for the IFMISSINGORNULL conditional function in QueryBuilder, providing feature parity with SQL++ for Mobile.
- **Added `Function_.ifMissingOrNull()` and `ifMissingOrNullAll()` methods** in `packages/cbl/lib/src/query/function.dart`
- Returns the first non-NULL and non-MISSING value from the provided expressions
- Supports 2-9 expressions via convenience method, unlimited via iterable method
- Implemented using `VariadicExpression` for multi-parameter support
- Includes comprehensive parameter validation
- **Added comprehensive test coverage** in `packages/cbl_e2e_tests/lib/src/query/query_builder_test.dart`
- Tests NULL, MISSING, and multiple expression scenarios
- Verified across all API variants (sync/async, main/worker isolates)
- Tests both convenience method and …

feat: add IFMISSINGORNULL function to QueryBuilder
